#!/bin/bash
# from https://gist.github.com/bcomnes/e756624dc1d126ba2eb6

# Fix SSH auth socket location so agent forwarding works with screen.
if test "$SSH_AUTH_SOCK" ; then
    #ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock.$(hostname)
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock.pat
fi
