if-shell "test ! -d ~/.tmux/plugins/tpm" \
   "run 'mkdir -p ~/.tmux/plugins/ && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-open'
set-option -g @plugin 'tmux-plugins/tmux-pain-control'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-sidebar'
set-option -g @plugin 'tmux-plugins/tmux-yank'

set-option -g @plugin 'catppuccin/tmux'
set-option -g @catppuccin_flavor 'frappe'
set-option -g @catppuccin_status_background "none"
set -g @catppuccin_window_background "none"
#set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_window_bg_color "none"
set -g @catppuccin_window_bg_color "none"
set -g @catppuccin_status_bg_color "none"

set-option -g @catppuccin_window_default_text "#W"
set-option -g @catppuccin_window_current_text "#W"

run '~/.tmux/plugins/tpm/tpm'

# THEME
#set -g status-bg default
set-option -g status-style bg=default
set-option -g status-left ""
set-option -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set-option -g status-right-length 100

# BINDINGS
bind-key a last-window            # sensible also sets PREFIX+PREFIX_LETTER (C^B+b)
bind-key c new-window -c "$HOME"  # redefine c to always go to $HOME
bind-key / copy-mode \; send ?    # faster upward search

set-option -g mouse on

#setw -g aggressive-resize off

set-option -g base-index 1
set-option -g renumber-windows on
set-option -g history-limit 500000
set-option -g escape-time 10

set-window-option -g mode-keys vi
